package vavi.util.logging.rococoa;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
/**
 * JNA Wrapper for library <b></b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface Library {
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int __WORDSIZE = 32;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT8_MAX = 127;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT16_MAX = 32767;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT32_MAX = 2147483647;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long INT64_MAX = 9223372036854775807L;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT8_MIN = -128;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT16_MIN = -32768;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT32_MIN = (-2147483647 - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long INT64_MIN = (-9223372036854775807L - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int UINT8_MAX = 255;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int UINT16_MAX = 65535;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long UINT32_MAX = 4294967295L;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long UINT64_MAX = -1L;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT_LEAST8_MIN = -128;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT_LEAST16_MIN = -32768;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT_LEAST32_MIN = (-2147483647 - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long INT_LEAST64_MIN = (-9223372036854775807L - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT_LEAST8_MAX = 127;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT_LEAST16_MAX = 32767;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT_LEAST32_MAX = 2147483647;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long INT_LEAST64_MAX = 9223372036854775807L;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int UINT_LEAST8_MAX = 255;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int UINT_LEAST16_MAX = 65535;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long UINT_LEAST32_MAX = 4294967295L;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long UINT_LEAST64_MAX = -1L;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT_FAST8_MIN = -128;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT_FAST16_MIN = -32768;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT_FAST32_MIN = (-2147483647 - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long INT_FAST64_MIN = (-9223372036854775807L - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT_FAST8_MAX = 127;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT_FAST16_MAX = 32767;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INT_FAST32_MAX = 2147483647;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long INT_FAST64_MAX = 9223372036854775807L;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int UINT_FAST8_MAX = 255;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int UINT_FAST16_MAX = 65535;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long UINT_FAST32_MAX = 4294967295L;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long UINT_FAST64_MAX = -1L;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INTPTR_MAX = 2147483647;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int INTPTR_MIN = (-2147483647 - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long UINTPTR_MAX = 4294967295L;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long INTMAX_MAX = (9223372036854775807L);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long UINTMAX_MAX = (-1L);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long INTMAX_MIN = (-(9223372036854775807L) - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int PTRDIFF_MIN = (-2147483647 - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int PTRDIFF_MAX = 2147483647;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long SIZE_MAX = 4294967295L;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	long RSIZE_MAX = (4294967295L >> 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int WCHAR_MAX = 0x7fffffff;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int WCHAR_MIN = (0x7fffffff - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int WINT_MIN = (-2147483647 - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int WINT_MAX = 2147483647;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int SIG_ATOMIC_MIN = (-2147483647 - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdint.h</i> */
	int SIG_ATOMIC_MAX = 2147483647;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_types.h</i> */
	int __DARWIN_WCHAR_MAX = 0x7fffffff;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_types.h</i> */
	int __DARWIN_WCHAR_MIN = (0x7fffffff - 1);
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_types.h</i> */
	int _FORTIFY_SOURCE = 2;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/Availability.h</i> */
	int __API_TO_BE_DEPRECATED = 100000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_0 = 1000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_1 = 1010;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_2 = 1020;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_3 = 1030;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_4 = 1040;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_5 = 1050;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_6 = 1060;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_7 = 1070;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_8 = 1080;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_9 = 1090;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_10 = 101000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_10_2 = 101002;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_10_3 = 101003;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_11 = 101100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_11_2 = 101102;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_11_3 = 101103;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_11_4 = 101104;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_12 = 101200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_12_1 = 101201;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_12_2 = 101202;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_12_4 = 101204;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_13 = 101300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_13_1 = 101301;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_13_2 = 101302;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_13_4 = 101304;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_14 = 101400;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_14_1 = 101401;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_14_4 = 101404;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_14_6 = 101406;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_15 = 101500;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_15_1 = 101501;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_15_4 = 101504;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_10_16 = 101600;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_11_0 = 110000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_11_1 = 110100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_11_3 = 110300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_11_4 = 110400;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_11_5 = 110500;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_11_6 = 110600;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_12_0 = 120000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __MAC_12_1 = 120100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_2_0 = 20000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_2_1 = 20100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_2_2 = 20200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_3_0 = 30000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_3_1 = 30100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_3_2 = 30200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_4_0 = 40000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_4_1 = 40100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_4_2 = 40200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_4_3 = 40300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_5_0 = 50000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_5_1 = 50100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_6_0 = 60000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_6_1 = 60100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_7_0 = 70000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_7_1 = 70100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_8_0 = 80000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_8_1 = 80100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_8_2 = 80200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_8_3 = 80300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_8_4 = 80400;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_9_0 = 90000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_9_1 = 90100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_9_2 = 90200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_9_3 = 90300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_10_0 = 100000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_10_1 = 100100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_10_2 = 100200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_10_3 = 100300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_11_0 = 110000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_11_1 = 110100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_11_2 = 110200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_11_3 = 110300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_11_4 = 110400;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_12_0 = 120000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_12_1 = 120100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_12_2 = 120200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_12_3 = 120300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_12_4 = 120400;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_13_0 = 130000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_13_1 = 130100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_13_2 = 130200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_13_3 = 130300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_13_4 = 130400;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_13_5 = 130500;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_13_6 = 130600;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_13_7 = 130700;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_14_0 = 140000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_14_1 = 140100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_14_2 = 140200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_14_3 = 140300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_14_5 = 140500;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_14_6 = 140600;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_14_7 = 140700;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_14_8 = 140800;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_15_0 = 150000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_15_1 = 150100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __IPHONE_15_2 = 150200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_9_0 = 90000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_9_1 = 90100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_9_2 = 90200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_10_0 = 100000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_10_0_1 = 100001;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_10_1 = 100100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_10_2 = 100200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_11_0 = 110000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_11_1 = 110100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_11_2 = 110200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_11_3 = 110300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_11_4 = 110400;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_12_0 = 120000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_12_1 = 120100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_12_2 = 120200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_12_3 = 120300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_12_4 = 120400;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_13_0 = 130000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_13_2 = 130200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_13_3 = 130300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_13_4 = 130400;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_14_0 = 140000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_14_1 = 140100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_14_2 = 140200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_14_3 = 140300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_14_5 = 140500;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_14_6 = 140600;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_14_7 = 140700;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_15_0 = 150000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_15_1 = 150100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __TVOS_15_2 = 150200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_1_0 = 10000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_2_0 = 20000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_2_1 = 20100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_2_2 = 20200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_3_0 = 30000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_3_1 = 30100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_3_1_1 = 30101;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_3_2 = 30200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_4_0 = 40000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_4_1 = 40100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_4_2 = 40200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_4_3 = 40300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_5_0 = 50000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_5_1 = 50100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_5_2 = 50200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_5_3 = 50300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_6_0 = 60000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_6_1 = 60100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_6_2 = 60200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_7_0 = 70000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_7_1 = 70100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_7_2 = 70200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_7_3 = 70300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_7_4 = 70400;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_7_5 = 70500;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_7_6 = 70600;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_8_0 = 80000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_8_1 = 80100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __WATCHOS_8_3 = 80300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_0 = 1000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_1 = 1010;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_2 = 1020;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_3 = 1030;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_4 = 1040;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_5 = 1050;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_6 = 1060;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_7 = 1070;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_8 = 1080;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_9 = 1090;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_10 = 101000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_10_2 = 101002;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_10_3 = 101003;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_11 = 101100;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_11_2 = 101102;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_11_3 = 101103;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_11_4 = 101104;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_12 = 101200;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_12_1 = 101201;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_12_2 = 101202;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_12_4 = 101204;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_13 = 101300;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_13_1 = 101301;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_13_2 = 101302;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_13_4 = 101304;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_14 = 101400;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_14_1 = 101401;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_14_4 = 101404;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_14_6 = 101406;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_15 = 101500;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_15_1 = 101501;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_X_VERSION_10_16 = 101600;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_VERSION_11_0 = 110000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int MAC_OS_VERSION_12_0 = 120000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __DRIVERKIT_19_0 = 190000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __DRIVERKIT_20_0 = 200000;
	/** <i>native declaration : /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/AvailabilityVersions.h</i> */
	int __DRIVERKIT_21_0 = 210000;
}
